{{- if eq .Values.configMapRequired "yes" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-{{ .Values.configMapName}}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    app: {{ .Values.appName }}
{{- with .Values.configMapData }}
data:
{{- toYaml . | trim | nindent 2 }}
{{- end }}
{{- end }}